{% set name = "condorpy" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2a8d9872f7fa45c33ef213e4612219924c8e411d046e5e4795da70ebeb7284e5

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - scp
    - paramiko

test:
  imports:
    - condorpy
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://pypi.org/project/condorpy/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A simple HTCondor Python interface.'
  description: |
    Condorpy is a wrapper for the command line interface (cli) of HTCondor 
    and enables creating submitting and monitoring HTCondor jobs from Python. 
    HTCondor must be installed to use condorpy.
  doc_url: http://www.tethysplatform.org/condorpy/
  dev_url: https://github.com/tethysplatform/condorpy

extra:
  recipe-maintainers:
    - swainn
