{% set name = "condorpy" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 70cd70471d0f4caaa17b0e4a61e7c5b872d796c7b743f38c0cc123c1ef601b0b

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - scp
    - paramiko

test:
  imports:
    - condorpy
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://pypi.org/project/condorpy/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A simple HTCondor Python interface.'
  description: |
    Condorpy is a wrapper for the command line interface (cli) of HTCondor 
    and enables creating submitting and monitoring HTCondor jobs from Python. 
    HTCondor must be installed to use condorpy.
  doc_url: http://www.tethysplatform.org/condorpy/
  dev_url: https://github.com/tethysplatform/condorpy

extra:
  recipe-maintainers:
    - swainn
